### ISSUE TITLE
images don't display

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [peter-tharwat/personal_website#2]
After a lot of tries to install and integrate `Imagick` to my setup, the images are downloaded successfully, but they don't show in the guests page.

they make like this error in the console

![Screen Shot 2021-09-17 at 01 02 32](https://user-images.githubusercontent.com/24838274/133691623-094c3246-67ae-43bd-bd2d-17d690191f46.png)

**Comment by peter-tharwat** [comment]
Hello Watheq 
Oh sorry , dont forget to link your storage to public via 
`php artisan storage:link`
i will add it to ReadMe file
and write how to install Imagick

**Comment by peter-tharwat** [comment]
And dont forget to add 
`
DEFAULT_IMAGE="${APP_URL}/images/default.png"
STORAGE_URL="${APP_URL}/storage"
`
to your .env file 
* added at recently

**Comment by peter-tharwat** [comment]
And dont forget to add those 2 lines of code to your .env file
DEFAULT_IMAGE="${APP_URL}/images/default.png"
STORAGE_URL="${APP_URL}/storage"

**Comment by WatheqAlshowaiter** [comment]
yeah, those lines did solve the problem... thank you so much
